# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - BotaniaAppStreamlitChemsKams

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://botaniastreamlitkamschems.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_18ab349cb4bb4d499ba1d79ab9b28243 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_83f379d37b944822a6329cfdfde81abe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: botaniastreamlitkamschems.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18ab349cb4bb4d499ba1d79ab9b28243 }}/streamlit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BotaniaAppStreamlitChemsKams'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_be338a90338f4d72a498c238c992bb8d }}
        images: 'botaniastreamlitkamschems.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_18ab349cb4bb4d499ba1d79ab9b28243 }}/streamlit:${{ github.sha }}'